name: build-win

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      ctestArgs:
        description: 'CTest arguments'

env:
  BUILD_TYPE: Release
  BUILD_PLATFORM: x64
  VERSION: 1.0.0

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true

    - name: Configure CMake
      working-directory: .\playground
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A x64 -DARCH=Win64

      # NOTE: The cmake build is forced to be single
      # configuration (either Debug or Release) but it
      #  must be specified when running tests on Windows
      # because of MSVC solution oddities

    - name: Build
      working-directory: .\playground
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: .\playground
      run: ctest --test-dir build ${{ github.event.inputs.ctestArgs }}
    
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{env.VERSION}}
        tag_name: ${{env.VERSION}}
        #body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:\a\podofo\podofo\playground\build\target\Release\podofo.dll
          asset_name: podofo.dll
          asset_content_type: application/x-windows-installer
